### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1

### ISSUE THREAD

**Issue by taoweiji** [joyrun/PullUpSwipeRefreshLayout#1]
```
Process: com.thejoyrun.swiperefreshlayout.demo, PID: 24028
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:225)
at android.widget.AbsListView.obtainView(AbsListView.java:2391)
at android.widget.ListView.makeAndAddView(ListView.java:1932)
at android.widget.ListView.fillDown(ListView.java:760)
at android.widget.ListView.fillGap(ListView.java:701)
at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5648)
at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4642)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
at android.view.Choreographer.doCallbacks(Choreographer.java:574)
at android.view.Choreographer.doFrame(Choreographer.java:543)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5114)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by nickylin** [comment]
is any one have same problem or any solutions?
